apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx-deployment-arm

spec:

  selector:

    matchLabels:

      app: nginx

  replicas: 2 # tells deployment to run 2 pods matching the template

  template:

    metadata:

      labels:

        app: nginx

    spec:

      containers:

      - name: nginx

        image: nginx:1.14.2
        resources:
          requests:
            cpu: '250m'
            memory: '64Mi'

        ports:

        - containerPort: 80
      nodeSelector:
        kubernetes.io/arch: arm64
